var annotated_dup =
[
    [ "ia", "namespaceia.html", [
      [ "client", "namespaceia_1_1client.html", [
        [ "ZappyAIClient", "classia_1_1client_1_1ZappyAIClient.html", "classia_1_1client_1_1ZappyAIClient" ]
      ] ],
      [ "launcher", "namespaceia_1_1launcher.html", [
        [ "ClientLauncher", "classia_1_1launcher_1_1ClientLauncher.html", "classia_1_1launcher_1_1ClientLauncher" ],
        [ "ManagedClient", "classia_1_1launcher_1_1ManagedClient.html", null ],
        [ "TeamRuntime", "classia_1_1launcher_1_1TeamRuntime.html", null ]
      ] ],
      [ "observation", "namespaceia_1_1observation.html", [
        [ "Observation", "classia_1_1observation_1_1Observation.html", "classia_1_1observation_1_1Observation" ]
      ] ],
      [ "parsing", "namespaceia_1_1parsing.html", [
        [ "LineBuffer", "classia_1_1parsing_1_1LineBuffer.html", "classia_1_1parsing_1_1LineBuffer" ],
        [ "ProtocolError", "classia_1_1parsing_1_1ProtocolError.html", null ]
      ] ],
      [ "strategy", "namespaceia_1_1strategy.html", [
        [ "State", "classia_1_1strategy_1_1State.html", null ],
        [ "Strategy", "classia_1_1strategy_1_1Strategy.html", "classia_1_1strategy_1_1Strategy" ]
      ] ],
      [ "test", "namespaceia_1_1test.html", [
        [ "FakeClient", "classia_1_1test_1_1FakeClient.html", "classia_1_1test_1_1FakeClient" ]
      ] ]
    ] ],
    [ "zappy", "namespacezappy.html", [
      [ "ArgParser", "classzappy_1_1ArgParser.html", "classzappy_1_1ArgParser" ],
      [ "Client", "classzappy_1_1Client.html", "classzappy_1_1Client" ],
      [ "ClientHandler", "classzappy_1_1ClientHandler.html", "classzappy_1_1ClientHandler" ],
      [ "CommandParser", "classzappy_1_1CommandParser.html", "classzappy_1_1CommandParser" ],
      [ "Commands", "classzappy_1_1Commands.html", "classzappy_1_1Commands" ],
      [ "Core", "classzappy_1_1Core.html", "classzappy_1_1Core" ],
      [ "Direction", "structzappy_1_1Direction.html", "structzappy_1_1Direction" ],
      [ "Egg", "structzappy_1_1Egg.html", "structzappy_1_1Egg" ],
      [ "ElevationRequirement", "structzappy_1_1ElevationRequirement.html", "structzappy_1_1ElevationRequirement" ],
      [ "FlagConfig", "structzappy_1_1FlagConfig.html", "structzappy_1_1FlagConfig" ],
      [ "Inventory", "classzappy_1_1Inventory.html", "classzappy_1_1Inventory" ],
      [ "Logger", "classzappy_1_1Logger.html", "classzappy_1_1Logger" ],
      [ "PendingCommand", "structzappy_1_1PendingCommand.html", "structzappy_1_1PendingCommand" ],
      [ "Player", "classzappy_1_1Player.html", "classzappy_1_1Player" ],
      [ "position", "structzappy_1_1position.html", "structzappy_1_1position" ],
      [ "ServerException", "classzappy_1_1ServerException.html", "classzappy_1_1ServerException" ],
      [ "Socket", "classzappy_1_1Socket.html", "classzappy_1_1Socket" ],
      [ "Team", "structzappy_1_1Team.html", "structzappy_1_1Team" ],
      [ "tile", "structzappy_1_1tile.html", "structzappy_1_1tile" ],
      [ "World", "classzappy_1_1World.html", "classzappy_1_1World" ]
    ] ],
    [ "Zappy", "namespaceZappy.html", [
      [ "AEventHandler", "classZappy_1_1AEventHandler.html", null ],
      [ "AMapEntity", "classZappy_1_1AMapEntity.html", "classZappy_1_1AMapEntity" ],
      [ "Appearance", "structZappy_1_1Appearance.html", "structZappy_1_1Appearance" ],
      [ "AssetCache", "classZappy_1_1AssetCache.html", "classZappy_1_1AssetCache" ],
      [ "Color", "structZappy_1_1Color.html", "structZappy_1_1Color" ],
      [ "ColorPalette", "classZappy_1_1ColorPalette.html", "classZappy_1_1ColorPalette" ],
      [ "CommandBuilder", "classZappy_1_1CommandBuilder.html", null ],
      [ "Core", "classZappy_1_1Core.html", "classZappy_1_1Core" ],
      [ "CubemapTexture", "classZappy_1_1CubemapTexture.html", "classZappy_1_1CubemapTexture" ],
      [ "Egg", "classZappy_1_1Egg.html", "classZappy_1_1Egg" ],
      [ "EggEventHandler", "classZappy_1_1EggEventHandler.html", "classZappy_1_1EggEventHandler" ],
      [ "EntityCommonHandler", "classZappy_1_1EntityCommonHandler.html", "classZappy_1_1EntityCommonHandler" ],
      [ "EntityKey", "structZappy_1_1EntityKey.html", "structZappy_1_1EntityKey" ],
      [ "EntityRenderer", "classZappy_1_1EntityRenderer.html", "classZappy_1_1EntityRenderer" ],
      [ "Event", "structZappy_1_1Event.html", "structZappy_1_1Event" ],
      [ "FreeCamera", "classZappy_1_1FreeCamera.html", "classZappy_1_1FreeCamera" ],
      [ "GameEventHandler", "classZappy_1_1GameEventHandler.html", "classZappy_1_1GameEventHandler" ],
      [ "GameState", "classZappy_1_1GameState.html", "classZappy_1_1GameState" ],
      [ "GraphicsContext", "classZappy_1_1GraphicsContext.html", "classZappy_1_1GraphicsContext" ],
      [ "GridPosition", "structZappy_1_1GridPosition.html", "structZappy_1_1GridPosition" ],
      [ "GroundProjection", "classZappy_1_1GroundProjection.html", "classZappy_1_1GroundProjection" ],
      [ "HandlerRegistry", "classZappy_1_1HandlerRegistry.html", "classZappy_1_1HandlerRegistry" ],
      [ "HudRenderer", "classZappy_1_1HudRenderer.html", "classZappy_1_1HudRenderer" ],
      [ "ICamera", "classZappy_1_1ICamera.html", "classZappy_1_1ICamera" ],
      [ "ICommandHandler", "classZappy_1_1ICommandHandler.html", "classZappy_1_1ICommandHandler" ],
      [ "IEntity", "classZappy_1_1IEntity.html", "classZappy_1_1IEntity" ],
      [ "IncantationEventHandler", "classZappy_1_1IncantationEventHandler.html", "classZappy_1_1IncantationEventHandler" ],
      [ "INetwork", "classZappy_1_1INetwork.html", "classZappy_1_1INetwork" ],
      [ "InputHandler", "classZappy_1_1InputHandler.html", "classZappy_1_1InputHandler" ],
      [ "IParser", "classZappy_1_1IParser.html", "classZappy_1_1IParser" ],
      [ "IProjection", "classZappy_1_1IProjection.html", "classZappy_1_1IProjection" ],
      [ "IRenderer", "classZappy_1_1IRenderer.html", "classZappy_1_1IRenderer" ],
      [ "LogMessage", "structZappy_1_1LogMessage.html", "structZappy_1_1LogMessage" ],
      [ "MainMenu", "classZappy_1_1MainMenu.html", "classZappy_1_1MainMenu" ],
      [ "Map", "classZappy_1_1Map.html", "classZappy_1_1Map" ],
      [ "MapEventHandler", "classZappy_1_1MapEventHandler.html", "classZappy_1_1MapEventHandler" ],
      [ "MapRenderer", "classZappy_1_1MapRenderer.html", "classZappy_1_1MapRenderer" ],
      [ "MenuConfig", "structZappy_1_1MenuConfig.html", "structZappy_1_1MenuConfig" ],
      [ "Mesh", "classZappy_1_1Mesh.html", "classZappy_1_1Mesh" ],
      [ "MeshData", "structZappy_1_1MeshData.html", "structZappy_1_1MeshData" ],
      [ "MessageParser", "classZappy_1_1MessageParser.html", "classZappy_1_1MessageParser" ],
      [ "Model", "structZappy_1_1Model.html", "structZappy_1_1Model" ],
      [ "ModelAnimation", "structZappy_1_1ModelAnimation.html", "structZappy_1_1ModelAnimation" ],
      [ "ModelAnimationChannel", "structZappy_1_1ModelAnimationChannel.html", "structZappy_1_1ModelAnimationChannel" ],
      [ "ModelLoader", "classZappy_1_1ModelLoader.html", "classZappy_1_1ModelLoader" ],
      [ "ModelNode", "structZappy_1_1ModelNode.html", "structZappy_1_1ModelNode" ],
      [ "ModelPrimitive", "structZappy_1_1ModelPrimitive.html", "structZappy_1_1ModelPrimitive" ],
      [ "ModelSkin", "structZappy_1_1ModelSkin.html", "structZappy_1_1ModelSkin" ],
      [ "ModelSlicer", "classZappy_1_1ModelSlicer.html", "classZappy_1_1ModelSlicer" ],
      [ "NamedColors", "structZappy_1_1NamedColors.html", null ],
      [ "NetworkService", "classZappy_1_1NetworkService.html", "classZappy_1_1NetworkService" ],
      [ "OrbitCamera", "classZappy_1_1OrbitCamera.html", "classZappy_1_1OrbitCamera" ],
      [ "PlanarProjection", "classZappy_1_1PlanarProjection.html", "classZappy_1_1PlanarProjection" ],
      [ "Primitives", "classZappy_1_1Primitives.html", null ],
      [ "Ray", "structZappy_1_1Ray.html", "structZappy_1_1Ray" ],
      [ "RenderContext", "structZappy_1_1RenderContext.html", "structZappy_1_1RenderContext" ],
      [ "RenderModel", "classZappy_1_1RenderModel.html", "classZappy_1_1RenderModel" ],
      [ "RenderSystem", "classZappy_1_1RenderSystem.html", "classZappy_1_1RenderSystem" ],
      [ "ResourceSet", "classZappy_1_1ResourceSet.html", "classZappy_1_1ResourceSet" ],
      [ "SceneHudRenderer", "classZappy_1_1SceneHudRenderer.html", "classZappy_1_1SceneHudRenderer" ],
      [ "SceneRenderer", "classZappy_1_1SceneRenderer.html", "classZappy_1_1SceneRenderer" ],
      [ "Shader", "classZappy_1_1Shader.html", "classZappy_1_1Shader" ],
      [ "SkyRenderer", "classZappy_1_1SkyRenderer.html", "classZappy_1_1SkyRenderer" ],
      [ "TcpSocket", "classZappy_1_1TcpSocket.html", "classZappy_1_1TcpSocket" ],
      [ "TeamEventHandler", "classZappy_1_1TeamEventHandler.html", "classZappy_1_1TeamEventHandler" ],
      [ "TextRenderer", "classZappy_1_1TextRenderer.html", "classZappy_1_1TextRenderer" ],
      [ "Texture", "classZappy_1_1Texture.html", "classZappy_1_1Texture" ],
      [ "Theme", "structZappy_1_1Theme.html", "structZappy_1_1Theme" ],
      [ "ThemeRegistry", "classZappy_1_1ThemeRegistry.html", "classZappy_1_1ThemeRegistry" ],
      [ "Tile", "classZappy_1_1Tile.html", "classZappy_1_1Tile" ],
      [ "TopDownCamera", "classZappy_1_1TopDownCamera.html", "classZappy_1_1TopDownCamera" ],
      [ "TorusProjection", "classZappy_1_1TorusProjection.html", "classZappy_1_1TorusProjection" ],
      [ "Transform", "structZappy_1_1Transform.html", "structZappy_1_1Transform" ],
      [ "Trantorian", "classZappy_1_1Trantorian.html", "classZappy_1_1Trantorian" ],
      [ "TrantorianEventHandler", "classZappy_1_1TrantorianEventHandler.html", "classZappy_1_1TrantorianEventHandler" ],
      [ "Window", "classZappy_1_1Window.html", "classZappy_1_1Window" ],
      [ "WorldPoint", "structZappy_1_1WorldPoint.html", "structZappy_1_1WorldPoint" ]
    ] ],
    [ "cgltf_accessor", "structcgltf__accessor.html", "structcgltf__accessor" ],
    [ "cgltf_accessor_sparse", "structcgltf__accessor__sparse.html", "structcgltf__accessor__sparse" ],
    [ "cgltf_animation", "structcgltf__animation.html", "structcgltf__animation" ],
    [ "cgltf_animation_channel", "structcgltf__animation__channel.html", "structcgltf__animation__channel" ],
    [ "cgltf_animation_sampler", "structcgltf__animation__sampler.html", "structcgltf__animation__sampler" ],
    [ "cgltf_anisotropy", "structcgltf__anisotropy.html", "structcgltf__anisotropy" ],
    [ "cgltf_asset", "structcgltf__asset.html", "structcgltf__asset" ],
    [ "cgltf_attribute", "structcgltf__attribute.html", "structcgltf__attribute" ],
    [ "cgltf_buffer", "structcgltf__buffer.html", "structcgltf__buffer" ],
    [ "cgltf_buffer_view", "structcgltf__buffer__view.html", "structcgltf__buffer__view" ],
    [ "cgltf_camera", "structcgltf__camera.html", "structcgltf__camera" ],
    [ "cgltf_camera_orthographic", "structcgltf__camera__orthographic.html", "structcgltf__camera__orthographic" ],
    [ "cgltf_camera_perspective", "structcgltf__camera__perspective.html", "structcgltf__camera__perspective" ],
    [ "cgltf_clearcoat", "structcgltf__clearcoat.html", "structcgltf__clearcoat" ],
    [ "cgltf_data", "structcgltf__data.html", "structcgltf__data" ],
    [ "cgltf_diffuse_transmission", "structcgltf__diffuse__transmission.html", "structcgltf__diffuse__transmission" ],
    [ "cgltf_dispersion", "structcgltf__dispersion.html", "structcgltf__dispersion" ],
    [ "cgltf_draco_mesh_compression", "structcgltf__draco__mesh__compression.html", "structcgltf__draco__mesh__compression" ],
    [ "cgltf_emissive_strength", "structcgltf__emissive__strength.html", "structcgltf__emissive__strength" ],
    [ "cgltf_extension", "structcgltf__extension.html", "structcgltf__extension" ],
    [ "cgltf_extras", "structcgltf__extras.html", "structcgltf__extras" ],
    [ "cgltf_file_options", "structcgltf__file__options.html", "structcgltf__file__options" ],
    [ "cgltf_image", "structcgltf__image.html", "structcgltf__image" ],
    [ "cgltf_ior", "structcgltf__ior.html", "structcgltf__ior" ],
    [ "cgltf_iridescence", "structcgltf__iridescence.html", "structcgltf__iridescence" ],
    [ "cgltf_light", "structcgltf__light.html", "structcgltf__light" ],
    [ "cgltf_material", "structcgltf__material.html", "structcgltf__material" ],
    [ "cgltf_material_mapping", "structcgltf__material__mapping.html", "structcgltf__material__mapping" ],
    [ "cgltf_material_variant", "structcgltf__material__variant.html", "structcgltf__material__variant" ],
    [ "cgltf_memory_options", "structcgltf__memory__options.html", "structcgltf__memory__options" ],
    [ "cgltf_mesh", "structcgltf__mesh.html", "structcgltf__mesh" ],
    [ "cgltf_mesh_gpu_instancing", "structcgltf__mesh__gpu__instancing.html", "structcgltf__mesh__gpu__instancing" ],
    [ "cgltf_meshopt_compression", "structcgltf__meshopt__compression.html", "structcgltf__meshopt__compression" ],
    [ "cgltf_morph_target", "structcgltf__morph__target.html", "structcgltf__morph__target" ],
    [ "cgltf_node", "structcgltf__node.html", "structcgltf__node" ],
    [ "cgltf_options", "structcgltf__options.html", "structcgltf__options" ],
    [ "cgltf_pbr_metallic_roughness", "structcgltf__pbr__metallic__roughness.html", "structcgltf__pbr__metallic__roughness" ],
    [ "cgltf_pbr_specular_glossiness", "structcgltf__pbr__specular__glossiness.html", "structcgltf__pbr__specular__glossiness" ],
    [ "cgltf_primitive", "structcgltf__primitive.html", "structcgltf__primitive" ],
    [ "cgltf_sampler", "structcgltf__sampler.html", "structcgltf__sampler" ],
    [ "cgltf_scene", "structcgltf__scene.html", "structcgltf__scene" ],
    [ "cgltf_sheen", "structcgltf__sheen.html", "structcgltf__sheen" ],
    [ "cgltf_skin", "structcgltf__skin.html", "structcgltf__skin" ],
    [ "cgltf_specular", "structcgltf__specular.html", "structcgltf__specular" ],
    [ "cgltf_texture", "structcgltf__texture.html", "structcgltf__texture" ],
    [ "cgltf_texture_transform", "structcgltf__texture__transform.html", "structcgltf__texture__transform" ],
    [ "cgltf_texture_view", "structcgltf__texture__view.html", "structcgltf__texture__view" ],
    [ "cgltf_transmission", "structcgltf__transmission.html", "structcgltf__transmission" ],
    [ "cgltf_volume", "structcgltf__volume.html", "structcgltf__volume" ],
    [ "gladGLversionStruct", "structgladGLversionStruct.html", "structgladGLversionStruct" ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", "structstbi__io__callbacks" ]
];