var hierarchy =
[
    [ "Zappy::Appearance", "structZappy_1_1Appearance.html", null ],
    [ "zappy::ArgParser", "classzappy_1_1ArgParser.html", null ],
    [ "Zappy::AssetCache", "classZappy_1_1AssetCache.html", null ],
    [ "Zappy::GameState::Broadcast", "structZappy_1_1GameState_1_1Broadcast.html", null ],
    [ "Zappy::MapRenderer::BroadcastPing", "structZappy_1_1MapRenderer_1_1BroadcastPing.html", null ],
    [ "Zappy::SceneRenderer::BroadcastPing", "structZappy_1_1SceneRenderer_1_1BroadcastPing.html", null ],
    [ "Zappy::HudRenderer::Button", "structZappy_1_1HudRenderer_1_1Button.html", null ],
    [ "Zappy::SceneHudRenderer::Button", "structZappy_1_1SceneHudRenderer_1_1Button.html", null ],
    [ "cgltf_accessor", "structcgltf__accessor.html", null ],
    [ "cgltf_accessor_sparse", "structcgltf__accessor__sparse.html", null ],
    [ "cgltf_animation", "structcgltf__animation.html", null ],
    [ "cgltf_animation_channel", "structcgltf__animation__channel.html", null ],
    [ "cgltf_animation_sampler", "structcgltf__animation__sampler.html", null ],
    [ "cgltf_anisotropy", "structcgltf__anisotropy.html", null ],
    [ "cgltf_asset", "structcgltf__asset.html", null ],
    [ "cgltf_attribute", "structcgltf__attribute.html", null ],
    [ "cgltf_buffer", "structcgltf__buffer.html", null ],
    [ "cgltf_buffer_view", "structcgltf__buffer__view.html", null ],
    [ "cgltf_camera", "structcgltf__camera.html", null ],
    [ "cgltf_camera_orthographic", "structcgltf__camera__orthographic.html", null ],
    [ "cgltf_camera_perspective", "structcgltf__camera__perspective.html", null ],
    [ "cgltf_clearcoat", "structcgltf__clearcoat.html", null ],
    [ "cgltf_data", "structcgltf__data.html", null ],
    [ "cgltf_diffuse_transmission", "structcgltf__diffuse__transmission.html", null ],
    [ "cgltf_dispersion", "structcgltf__dispersion.html", null ],
    [ "cgltf_draco_mesh_compression", "structcgltf__draco__mesh__compression.html", null ],
    [ "cgltf_emissive_strength", "structcgltf__emissive__strength.html", null ],
    [ "cgltf_extension", "structcgltf__extension.html", null ],
    [ "cgltf_extras", "structcgltf__extras.html", null ],
    [ "cgltf_file_options", "structcgltf__file__options.html", null ],
    [ "cgltf_image", "structcgltf__image.html", null ],
    [ "cgltf_ior", "structcgltf__ior.html", null ],
    [ "cgltf_iridescence", "structcgltf__iridescence.html", null ],
    [ "cgltf_light", "structcgltf__light.html", null ],
    [ "cgltf_material", "structcgltf__material.html", null ],
    [ "cgltf_material_mapping", "structcgltf__material__mapping.html", null ],
    [ "cgltf_material_variant", "structcgltf__material__variant.html", null ],
    [ "cgltf_memory_options", "structcgltf__memory__options.html", null ],
    [ "cgltf_mesh", "structcgltf__mesh.html", null ],
    [ "cgltf_mesh_gpu_instancing", "structcgltf__mesh__gpu__instancing.html", null ],
    [ "cgltf_meshopt_compression", "structcgltf__meshopt__compression.html", null ],
    [ "cgltf_morph_target", "structcgltf__morph__target.html", null ],
    [ "cgltf_node", "structcgltf__node.html", null ],
    [ "cgltf_options", "structcgltf__options.html", null ],
    [ "cgltf_pbr_metallic_roughness", "structcgltf__pbr__metallic__roughness.html", null ],
    [ "cgltf_pbr_specular_glossiness", "structcgltf__pbr__specular__glossiness.html", null ],
    [ "cgltf_primitive", "structcgltf__primitive.html", null ],
    [ "cgltf_sampler", "structcgltf__sampler.html", null ],
    [ "cgltf_scene", "structcgltf__scene.html", null ],
    [ "cgltf_sheen", "structcgltf__sheen.html", null ],
    [ "cgltf_skin", "structcgltf__skin.html", null ],
    [ "cgltf_specular", "structcgltf__specular.html", null ],
    [ "cgltf_texture", "structcgltf__texture.html", null ],
    [ "cgltf_texture_transform", "structcgltf__texture__transform.html", null ],
    [ "cgltf_texture_view", "structcgltf__texture__view.html", null ],
    [ "cgltf_transmission", "structcgltf__transmission.html", null ],
    [ "cgltf_volume", "structcgltf__volume.html", null ],
    [ "zappy::Client", "classzappy_1_1Client.html", null ],
    [ "zappy::ClientHandler", "classzappy_1_1ClientHandler.html", null ],
    [ "ia.launcher.ClientLauncher", "classia_1_1launcher_1_1ClientLauncher.html", null ],
    [ "Zappy::Color", "structZappy_1_1Color.html", null ],
    [ "Zappy::ColorPalette", "classZappy_1_1ColorPalette.html", null ],
    [ "Zappy::CommandBuilder", "classZappy_1_1CommandBuilder.html", null ],
    [ "zappy::CommandParser", "classzappy_1_1CommandParser.html", null ],
    [ "zappy::Commands", "classzappy_1_1Commands.html", null ],
    [ "Zappy::Core", "classZappy_1_1Core.html", null ],
    [ "zappy::Core", "classzappy_1_1Core.html", null ],
    [ "Zappy::CubemapTexture", "classZappy_1_1CubemapTexture.html", null ],
    [ "zappy::Direction", "structzappy_1_1Direction.html", null ],
    [ "Zappy::RenderModel::DrawItem", "structZappy_1_1RenderModel_1_1DrawItem.html", null ],
    [ "zappy::Egg", "structzappy_1_1Egg.html", null ],
    [ "zappy::ElevationRequirement", "structzappy_1_1ElevationRequirement.html", null ],
    [ "Zappy::SceneRenderer::EntityAnim", "structZappy_1_1SceneRenderer_1_1EntityAnim.html", null ],
    [ "Zappy::EntityKey", "structZappy_1_1EntityKey.html", null ],
    [ "Zappy::Event", "structZappy_1_1Event.html", null ],
    [ "std::exception", null, [
      [ "Zappy::AssetCache::AssetCacheException", "classZappy_1_1AssetCache_1_1AssetCacheException.html", null ],
      [ "Zappy::Core::CoreException", "classZappy_1_1Core_1_1CoreException.html", null ],
      [ "Zappy::CubemapTexture::CubemapException", "classZappy_1_1CubemapTexture_1_1CubemapException.html", null ],
      [ "Zappy::GraphicsContext::GraphicsContextException", "classZappy_1_1GraphicsContext_1_1GraphicsContextException.html", null ],
      [ "Zappy::INetwork::INetworkException", "classZappy_1_1INetwork_1_1INetworkException.html", [
        [ "Zappy::TcpSocket::TcpSocketException", "classZappy_1_1TcpSocket_1_1TcpSocketException.html", null ]
      ] ],
      [ "Zappy::MainMenu::MainMenuException", "classZappy_1_1MainMenu_1_1MainMenuException.html", null ],
      [ "Zappy::Mesh::MeshException", "classZappy_1_1Mesh_1_1MeshException.html", null ],
      [ "Zappy::ModelLoader::ModelLoaderException", "classZappy_1_1ModelLoader_1_1ModelLoaderException.html", null ],
      [ "Zappy::NetworkService::NetworkServiceException", "classZappy_1_1NetworkService_1_1NetworkServiceException.html", null ],
      [ "Zappy::RenderModel::RenderModelException", "classZappy_1_1RenderModel_1_1RenderModelException.html", null ],
      [ "Zappy::RenderSystem::RenderSystemException", "classZappy_1_1RenderSystem_1_1RenderSystemException.html", null ],
      [ "Zappy::Shader::ShaderException", "classZappy_1_1Shader_1_1ShaderException.html", null ],
      [ "Zappy::TextRenderer::TextRendererException", "classZappy_1_1TextRenderer_1_1TextRendererException.html", null ],
      [ "Zappy::Texture::TextureException", "classZappy_1_1Texture_1_1TextureException.html", null ],
      [ "Zappy::Window::WindowException", "classZappy_1_1Window_1_1WindowException.html", null ],
      [ "zappy::ServerException", "classzappy_1_1ServerException.html", null ]
    ] ],
    [ "ia.test.FakeClient", "classia_1_1test_1_1FakeClient.html", null ],
    [ "zappy::FlagConfig", "structzappy_1_1FlagConfig.html", null ],
    [ "Zappy::GameState", "classZappy_1_1GameState.html", null ],
    [ "gladGLversionStruct", "structgladGLversionStruct.html", null ],
    [ "Zappy::TextRenderer::Glyph", "structZappy_1_1TextRenderer_1_1Glyph.html", null ],
    [ "Zappy::GraphicsContext", "classZappy_1_1GraphicsContext.html", null ],
    [ "Zappy::GridPosition", "structZappy_1_1GridPosition.html", null ],
    [ "Zappy::HandlerRegistry", "classZappy_1_1HandlerRegistry.html", null ],
    [ "Zappy::ICamera", "classZappy_1_1ICamera.html", [
      [ "Zappy::FreeCamera", "classZappy_1_1FreeCamera.html", null ],
      [ "Zappy::OrbitCamera", "classZappy_1_1OrbitCamera.html", null ],
      [ "Zappy::TopDownCamera", "classZappy_1_1TopDownCamera.html", null ]
    ] ],
    [ "Zappy::ICommandHandler", "classZappy_1_1ICommandHandler.html", [
      [ "Zappy::AEventHandler", "classZappy_1_1AEventHandler.html", [
        [ "Zappy::EggEventHandler", "classZappy_1_1EggEventHandler.html", null ],
        [ "Zappy::EntityCommonHandler", "classZappy_1_1EntityCommonHandler.html", null ],
        [ "Zappy::GameEventHandler", "classZappy_1_1GameEventHandler.html", null ],
        [ "Zappy::IncantationEventHandler", "classZappy_1_1IncantationEventHandler.html", null ],
        [ "Zappy::MapEventHandler", "classZappy_1_1MapEventHandler.html", null ],
        [ "Zappy::TeamEventHandler", "classZappy_1_1TeamEventHandler.html", null ],
        [ "Zappy::TrantorianEventHandler", "classZappy_1_1TrantorianEventHandler.html", null ]
      ] ]
    ] ],
    [ "Zappy::IEntity", "classZappy_1_1IEntity.html", [
      [ "Zappy::AMapEntity", "classZappy_1_1AMapEntity.html", [
        [ "Zappy::Egg", "classZappy_1_1Egg.html", null ],
        [ "Zappy::Trantorian", "classZappy_1_1Trantorian.html", null ]
      ] ]
    ] ],
    [ "Zappy::INetwork", "classZappy_1_1INetwork.html", [
      [ "Zappy::TcpSocket", "classZappy_1_1TcpSocket.html", null ]
    ] ],
    [ "Zappy::InputHandler", "classZappy_1_1InputHandler.html", null ],
    [ "zappy::Inventory", "classzappy_1_1Inventory.html", null ],
    [ "Zappy::IParser", "classZappy_1_1IParser.html", [
      [ "Zappy::MessageParser", "classZappy_1_1MessageParser.html", null ]
    ] ],
    [ "Zappy::IProjection", "classZappy_1_1IProjection.html", [
      [ "Zappy::GroundProjection", "classZappy_1_1GroundProjection.html", null ],
      [ "Zappy::PlanarProjection", "classZappy_1_1PlanarProjection.html", null ],
      [ "Zappy::TorusProjection", "classZappy_1_1TorusProjection.html", null ]
    ] ],
    [ "Zappy::IRenderer", "classZappy_1_1IRenderer.html", [
      [ "Zappy::EntityRenderer", "classZappy_1_1EntityRenderer.html", null ],
      [ "Zappy::HudRenderer", "classZappy_1_1HudRenderer.html", null ],
      [ "Zappy::MapRenderer", "classZappy_1_1MapRenderer.html", null ],
      [ "Zappy::SceneHudRenderer", "classZappy_1_1SceneHudRenderer.html", null ],
      [ "Zappy::SceneRenderer", "classZappy_1_1SceneRenderer.html", null ],
      [ "Zappy::SkyRenderer", "classZappy_1_1SkyRenderer.html", null ]
    ] ],
    [ "ia.parsing.LineBuffer", "classia_1_1parsing_1_1LineBuffer.html", null ],
    [ "zappy::Logger", "classzappy_1_1Logger.html", null ],
    [ "Zappy::LogMessage", "structZappy_1_1LogMessage.html", null ],
    [ "Zappy::MainMenu", "classZappy_1_1MainMenu.html", null ],
    [ "ia.launcher.ManagedClient", "classia_1_1launcher_1_1ManagedClient.html", null ],
    [ "Zappy::Map", "classZappy_1_1Map.html", null ],
    [ "Zappy::MenuConfig", "structZappy_1_1MenuConfig.html", null ],
    [ "Zappy::Mesh", "classZappy_1_1Mesh.html", null ],
    [ "Zappy::MeshData", "structZappy_1_1MeshData.html", null ],
    [ "Zappy::Model", "structZappy_1_1Model.html", null ],
    [ "Zappy::ModelAnimation", "structZappy_1_1ModelAnimation.html", null ],
    [ "Zappy::ModelAnimationChannel", "structZappy_1_1ModelAnimationChannel.html", null ],
    [ "Zappy::ModelLoader", "classZappy_1_1ModelLoader.html", null ],
    [ "Zappy::ModelNode", "structZappy_1_1ModelNode.html", null ],
    [ "Zappy::ModelPrimitive", "structZappy_1_1ModelPrimitive.html", null ],
    [ "Zappy::ModelSkin", "structZappy_1_1ModelSkin.html", null ],
    [ "Zappy::ModelSlicer", "classZappy_1_1ModelSlicer.html", null ],
    [ "Zappy::NamedColors", "structZappy_1_1NamedColors.html", null ],
    [ "Zappy::NetworkService", "classZappy_1_1NetworkService.html", null ],
    [ "ia.observation.Observation", "classia_1_1observation_1_1Observation.html", null ],
    [ "zappy::PendingCommand", "structzappy_1_1PendingCommand.html", null ],
    [ "zappy::Player", "classzappy_1_1Player.html", null ],
    [ "zappy::position", "structzappy_1_1position.html", null ],
    [ "Zappy::Primitives", "classZappy_1_1Primitives.html", null ],
    [ "Zappy::Ray", "structZappy_1_1Ray.html", null ],
    [ "Zappy::MainMenu::Rect", "structZappy_1_1MainMenu_1_1Rect.html", null ],
    [ "Zappy::RenderContext", "structZappy_1_1RenderContext.html", null ],
    [ "Zappy::RenderModel", "classZappy_1_1RenderModel.html", null ],
    [ "Zappy::RenderSystem", "classZappy_1_1RenderSystem.html", null ],
    [ "Zappy::ResourceSet", "classZappy_1_1ResourceSet.html", null ],
    [ "Zappy::Shader", "classZappy_1_1Shader.html", null ],
    [ "zappy::Socket", "classzappy_1_1Socket.html", null ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", null ],
    [ "ia.strategy.Strategy", "classia_1_1strategy_1_1Strategy.html", null ],
    [ "zappy::Team", "structzappy_1_1Team.html", null ],
    [ "ia.launcher.TeamRuntime", "classia_1_1launcher_1_1TeamRuntime.html", null ],
    [ "Zappy::TextRenderer", "classZappy_1_1TextRenderer.html", null ],
    [ "Zappy::Texture", "classZappy_1_1Texture.html", null ],
    [ "Zappy::Theme", "structZappy_1_1Theme.html", null ],
    [ "Zappy::ThemeRegistry", "classZappy_1_1ThemeRegistry.html", null ],
    [ "zappy::tile", "structzappy_1_1tile.html", null ],
    [ "Zappy::Tile", "classZappy_1_1Tile.html", null ],
    [ "Zappy::Transform", "structZappy_1_1Transform.html", null ],
    [ "ValueError", null, [
      [ "ia.parsing.ProtocolError", "classia_1_1parsing_1_1ProtocolError.html", null ]
    ] ],
    [ "Zappy::Window", "classZappy_1_1Window.html", null ],
    [ "zappy::World", "classzappy_1_1World.html", null ],
    [ "Zappy::WorldPoint", "structZappy_1_1WorldPoint.html", null ],
    [ "ia.client.ZappyAIClient", "classia_1_1client_1_1ZappyAIClient.html", null ],
    [ "Enum", null, [
      [ "ia.strategy.State", "classia_1_1strategy_1_1State.html", null ]
    ] ]
];