name: CI

on:
  push:
    branches:
      - dev
      - server/tests/**
  pull_request:
    branches:
      - dev

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  build:
    name: Build
    if: github.repository == 'theo-futol/Zappy'
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update &&
          sudo apt install -y libx11-dev libxrandr-dev libxcursor-dev libxi-dev libxext-dev libxinerama-dev libxss-dev libgl1-mesa-dev libudev-dev libmbedtls-dev libfreetype-dev libssh2-1-dev libharfbuzz-dev libcriterion-dev
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run build
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install dependencies
        run: |
          sudo apt update &&
          sudo apt install -y libx11-dev libxrandr-dev libxcursor-dev libxi-dev libxext-dev libxinerama-dev libxss-dev libgl1-mesa-dev libudev-dev libmbedtls-dev libfreetype-dev libssh2-1-dev libharfbuzz-dev libcriterion-dev gcovr
      - name: check
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: test
        run: npm run test
